### ISSUE TITLE
regression: all commands return exit code 1

### ISSUE THREAD

**Issue by stardust85** [stardust85/repositorytools#18]
caused by https://github.com/stardust85/repositorytools/pull/17

How to reproduce (unix):
echo foo > foo
artifact upload foo test com.example
echo $?

expected result:
upload succeeds
return code 0

current result:
upload succeeds
return code 1

**Comment by tantale** [comment]
If fact, exit code is not handled: the return value of ``artifact.ArtifactCLI().run()`` is not used except in tests (or may be in client code – if any exist). So you need to add an explicit ``sys.exit(0)``.

Why it returns always *1*? Because of the definition of the entry point (see ``bin/artifact`` in your virtualenv):

```python
__requires__ = 'repositorytools'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('repositorytools', 'console_scripts', 'artifact')()
    )
```

The script calls ``artifact.ArtifactCLI().run()`` and use the return value as an exit code.

If it returns an integer, you'll get this exit code (module 128 and a sign).

```bash
$ python -c "import sys; sys.exit(0);"
$ echo $?
0

$ python -c "import sys; sys.exit(12);"
$ echo $?
12
```

But if the return value is not an integer you'll always get 1 (and a message is displayed).

```bash
$ python -c "import sys; sys.exit('bye.');"
bye.
$ echo $?
1
```

To make the entry points works, you need to return 0 in the ``repositorytools.cli.common.CLI.__call__`` method:

```python
    def __call__(self, *args):
        self.run(*args)
        return 0  # exit code
```

**Comment by stardust85** [comment]
Amazing investigation. Can you please prepare a pull request? Nothing else than tests uses return codes from the run() method AFAIK. Don't forget to put yourself to AUTHORS file in root directory (and please add me there as well :) I'd like to release a bugfix version by end of this week.

**Comment by tantale** [comment]
To list all the contributors:

```bash
git log --format='%aN <%aE>' | awk '{arr[$0]++} END{for (i in arr){print arr[i], i;}}' | sort -rn | cut -d\  -f2-
```

Source: http://www.commandlinefu.com/commands/view/4519/list-all-authors-of-a-particular-git-project

**Comment by tantale** [comment]
What do you think of this kind of ``AUTHORS.rst`` file:

```rst
=======
Credits
=======

Development Lead
----------------

* Michel SAMIA <stardust1985@gmail.com>

Contributors
------------

* Laurent LAPORTE <tantale.solutions@gmail.com>
```

**Comment by stardust85** [comment]
Perfect, exactly what I was thinking of. Maybe that file isn't necessary (git log works well), but I wanted to use it to motivate people for contributions :)
